# -*- coding: utf-8 -*-
"""cars.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TcSGtY1vH3gmAdZRLOLwvASi-YLCabJ6
"""



import pandas as pd
data=pd.read_csv(r'cars.csv')
print(data)

data["Cylinders"].fillna(data["Cylinders"].mean(),inplace=True)

print(data.isnull().sum())

make_count=data["Make"].value_counts()
print(make_count)

filter_records=data[data["Origin"].isin(["Asia","Europe"])]
print(filter_records)

data_w=data[data["Weight"]<=4000]
print(data_w)

data['MPG_City']+=3
print(data["MPG_City"])